backend:
  name: github
  repo: Fatihyal/manus-ai-web
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Sayfalar"
    files:
      - label: "Ana Sayfa"
        name: "home"
        file: "../index.html"
        fields:
          - { label: "Başlık", name: "title", widget: "string" }
          - { label: "İçerik", name: "body", widget: "markdown" }
